# Site
repository: rapop/rapop.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

kramdown:
  input: Kramdown

# Personal info
name: Radu Popescu
title: Robotics Software Engineer
email: radupopescu100@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  rapop
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: radu-popescu-920479114
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: profreestylefoot
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Sciencedirect
  icon: fas fa-globe
  url: https://www.sciencedirect.com/science/article/abs/pii/S0957415821000015?via%3Dihub
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile4.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Radu and I'm a robotics software engineer. I hold a master of science in robotics from [Ecole Polytechnique de Montreal](https://www.polymtl.ca/){:target="_blank" rel="noopener"}. As well as working in research I also have experience working in an agile team delivering production code for robotic applications.   

  I am most skilled in: <mark>C++</mark>, <mark>Python</mark> and  <mark>ROS</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Omnirobotic
        link: omnirobotic.com
        # link_text: boringcompany.com
        sub_title: Robotics Software Engineer
        caption: November 2020 - October 2022
        quote: >
          Changing the manufacturing industry with autonomous industrial robots for painting, powder coating, welding, sanding and milling. 
        description: | # this will include new lines to allow paragraphs
            I helped develop the overall platform and the motion planning framework for autonomous robotic arms supporting robots like the FANUC or the UR.

            Skills: <mark>C++</mark> <mark>Python</mark> <mark>Ubuntu</mark> <mark>Cmake</mark> <mark>Algorithms</mark> <mark>SOLID design</mark> <mark>Gtest</mark> <mark>Gmock</mark> <mark>pytest</mark> <mark>Git</mark> <mark>Agile (retro, daily, planning, sprint reviews)</mark> <mark>Multithreading</mark> <mark>Networking</mark> <mark>OMPL</mark> <mark>Moveit</mark> <mark>Docker</mark> <mark>Robotics simulation</mark>

      - layout: left
        title: Humanitas Solutions
        link: humanitas.io
        # link_text: boringcompany.com
        sub_title: Robotics Software Engineer
        caption: May 2020 - October 2020
        quote: >
          Using technology to help connect people. 
        description: | # this will include new lines to allow paragraphs
            During the 2020 pandemic, I helped create a geolocation solution for indoor localization of doctors and patients in hospitals.

            Skills:  <mark>C++</mark> <mark>C programming for embedded DWM1001 modules</mark> <mark>Python</mark> <mark>Ubuntu</mark> <mark>UWB</mark> <mark>Range-based localization algorithms</mark> <mark>Docker</mark> <mark>Git</mark>  <mark>Gazebo</mark> <mark>Robotics simulation</mark>

      - layout: left
        title: Intelligent Systems and Mechatronics Lab
        link: polymtl.ca
        # link_text: boringcompany.com
        sub_title: Robotics researcher
        caption: January 2019 - May 2020
        quote: >
          Changing people's lives with robotics.  
        description: | # this will include new lines to allow paragraphs
            In the context of rehabilitating disabled people, my goal was to design and develop an autonomous quadrotor table tennis player. This poject involved pushing the boundaries in terms of aggressive control and precise trajectory tracking for quadrotors.    

            I published an [article](https://www.sciencedirect.com/science/article/abs/pii/S0957415821000015#!){:target="_blank" rel="noopener"} about it in Mechatronics Journal. 

            Skills: <mark>C++</mark> <mark>Python</mark> <mark>ROS</mark> <mark>Gazebo</mark> <mark>Ubuntu</mark> <mark>Control algorithms</mark> <mark>iLQR</mark> <mark>Robotics hardware</mark> <mark>Motion capture system</mark> <mark>CAD design</mark> <mark>Research</mark>



            Software architecture:   
            ![Software architecture](/images/software_architecture.png "Software architecture")



            Hitting motion in simulation and on the real quadrotor:
            ![VREP simulation](/images/Vrep_simulation.gif "VREP simulation")   
            ![Hitting motion](/images/hitting_motion.gif "Hitting motion")


  - title: Other projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Decentralized autonomous lawn mower
        link: github.com/rapop/decentralized-autonomouse-mower-service
        # link_text: Project Website
        icon: fab fa-github
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:

      - Rock climbing

      - Gaming

      - Knitting

      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
