# Site
repository: rapop/rapop.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

kramdown:
  input: Kramdown

# Personal info
name: Radu Popescu
title: Robotics Software Engineer
email: radupopescu100@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  rapop
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: radu-popescu-920479114
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: profreestylefoot
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Sciencedirect
  icon: fas fa-globe
  url: https://www.sciencedirect.com/science/article/abs/pii/S0957415821000015?via%3Dihub
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile4.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Radu and I'm a robotics software engineer. I hold a master of science in robotics from [Ecole Polytechnique de Montreal](https://www.polymtl.ca/){:target="_blank" rel="noopener"}. As well as working in research I also have experience working in an agile team delivering production code for robotic applications.   

  I am most skilled in: <mark>C++</mark>, <mark>Python</mark> and  <mark>ROS</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Omnirobotic
        link: omnirobotic.com
        # link_text: boringcompany.com
        sub_title: Robotics Software Engineer
        caption: November 2020 - October 2022
        quote: >
          Changing the manufacturing industry with autonomous industrial robots for painting, powder coating, welding, sanding and milling. 
        description: | # this will include new lines to allow paragraphs
            I helped develop the overall platform and the motion planning framework for autonomous robotic arms supporting robots like the FANUC or the UR.

            Skills: <mark>C++</mark> <mark>Python</mark> <mark>Ubuntu</mark> <mark>Cmake</mark> <mark>Algorithms</mark> <mark>SOLID design</mark> <mark>Gtest</mark> <mark>Gmock</mark> <mark>pytest</mark> <mark>Git</mark> <mark>Agile (retro, daily, planning, sprint reviews)</mark> <mark>Multithreading</mark> <mark>Networking</mark> <mark>OMPL</mark> <mark>Moveit</mark> <mark>Docker</mark> <mark>Robotics simulation</mark>

            ![](/images/paintrobot.png){: width="50%"}{: .align-center}

      - layout: left
        title: Humanitas Solutions
        link: humanitas.io
        # link_text: boringcompany.com
        sub_title: Robotics Software Engineer
        caption: May 2020 - October 2020
        quote: >
          Using technology to help connect people. 
        description: | # this will include new lines to allow paragraphs
            During the 2020 pandemic, I helped create a geolocation solution for indoor localization of doctors and patients in hospitals.

            Skills:  <mark>C++</mark> <mark>C programming for embedded DWM1001 modules</mark> <mark>Python</mark> <mark>Ubuntu</mark> <mark>UWB</mark> <mark>Range-based localization algorithms</mark> <mark>Docker</mark> <mark>Git</mark>  <mark>Gazebo</mark> <mark>Robotics simulation</mark>

            ![](/images/triangulation.png){: width="50%"} 

      - layout: left
        title: Intelligent Systems and Mechatronics Lab
        link: polymtl.ca
        # link_text: boringcompany.com
        sub_title: Robotics researcher
        caption: January 2019 - May 2020
        quote: >
          Changing people's lives with robotics.  
        description: | # this will include new lines to allow paragraphs
            In the context of rehabilitating disabled people, my goal was to design and develop an autonomous quadrotor table tennis player. This project involved pushing the boundaries in terms of aggressive control and precise trajectory tracking for quadrotors.    

            I published an [article](https://www.sciencedirect.com/science/article/abs/pii/S0957415821000015#!){:target="_blank" rel="noopener"} about it in Mechatronics Journal. 

            Skills: <mark>C++</mark> <mark>Python</mark> <mark>ROS</mark> <mark>Gazebo</mark> <mark>Ubuntu</mark> <mark>Control algorithms</mark> <mark>iLQR</mark> <mark>Robotics hardware</mark> <mark>Motion capture system</mark> <mark>CAD design</mark> <mark>Research</mark>

            Software architecture:   
            
            ![Software architecture](/images/software_architecture.png "Software architecture"){: width="80%"}

            Hitting motion in simulation and on the real quadrotor:

            ![VREP simulation](/images/Vrep_simulation.gif "VREP simulation"){: width="80%"}   

            ![Hitting motion](/images/hitting_motion.gif "Hitting motion"){: width="80%"}


  - title: Other projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Decentralized autonomous lawn mower
        link: github.com/rapop/decentralized-autonomouse-mower-service
        # link_text: Project Website
        additional_links:
          - title:  gihub page for project
            icon: fab fa-github
            url: github.com/rapop/decentralized-autonomouse-mower-service
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one thing robots should do instead of humans! 
        description: | # this will include new lines to allow paragraphs
          I did this project in a team of 2 wanting to grow it in a viable product (at least the part without the blockchain technology). We also participated at the 2022 Chainlink Spring Hackathon and won multiple prizes! Check it out on [devpost](https://devpost.com/software/decentralized-autonomous-lawn-mower){:target="_blank" rel="noopener"}.

          Skills: <mark>C++</mark> <mark>Python</mark> <mark>ROS</mark> <mark>Gazebo</mark> <mark>Ubuntu</mark> <mark>Control algorithms</mark> <mark>Solidity</mark> <mark>Brownie</mark> <mark>Chainlink external adapters</mark>

          ![Autonomous Lawn Mower](/images/autonomous_mower.png "Autonomous Lawn Mower"){: width="50%"}

          Prizes:

          - WINNER Chainlink Top Quality Projects [$750 each]
          - WINNER Filecoin - Runners up - $12,500 [$1000 each]

          ![Chainlink Hackathon](/images/chainlink.png "Chainlink Hackathon"){: width="30%"}


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ecole Polytechnique de Montreal
        caption: 2019 - 2020
        sub_title: MSc Robotics
        description: | # this will include new lines to allow paragraphs
          I had some courses in robotics and optimal control but most of my time was invested towards research. 

          I was a member of *Elikos*, an engineering student club in the field of aerial robotics who participates in the
          *Unmanned Systems Canada Student* annual competition. 

      - layout: left
        title: Ecole Polytechnique de Montreal
        caption: 2014 - 2018
        sub_title: BEng Aerospace Engineering
        description: | # this will include new lines to allow paragraphs
          Mention of Excellence for outstanding academic results.

          I did an engineering internship at [Bombardier](https://bombardier.com){:target="_blank" rel="noopener"} which is one of the biggest aircraft manufacturer. 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in robotics and software engineering some of my other interests and hobbies are:

      - Bodybuilding

      - Hiking

      - Traveling

      - Watching high quality cinematographic movies

      Transfagarasan, Romania  

      ![](/images/hike1.jpg){: width="50%"}{:style="text-align: center;"}

      ![](/images/hike2.jpg){: width="50%" .align-center}

      Blade Runner 2022

      ![](/images/blade.jpg){: width="50%" .align-center}


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
